LATENT_DIM = 512
BATCH_SIZE = 128 # Contrastive batch
MICROBATCH_SIZE = 8

LEARNING_RATE = 2e-3

LOAD_CHECKPOINT = True
ITERATIONS = 80000
LOG_INTERVAL = 2
CHECKPOINT_INTERVAL = 50
# Geometric ones are mostly fine
# Disabled color transformations
AUG_PROB = 0.297
AUG_XFLIP = 1
AUG_ROT90 = 0
AUG_XINT = 1
AUG_SCALE = 1
AUG_ROT = 0
AUG_ANISO = 1
AUG_XFRAC = 1
AUG_BRIGHTNESS = 0
AUG_CONTRAST = 0
AUG_HUE = 0
AUG_SAT = 0
AUG_LUMAFLIP = 0
